# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-10 19:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='sort',
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='recipient',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
